ARG version 
FROM almalinux:${version:-9} 
ENV course="devops" \
    duration="120hrs" 
ARG trainer="sivakumar"
RUN echo "Hi, iam learning course:${course}, duration is:${duration}, and trainer is:${trainer}"
CMD ["sleep", "1000"]